name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    uses: ./.github/workflows/build.yml
    with:
      test: true

  build-docs:
    uses: ./.github/workflows/build-docs.yml
    with:
      version: latest
