name: pr

on:
  pull_request:
    types:
      - review_requested
      - ready_for_review
      - synchronize

jobs:
  build-test:
    uses: ./.github/workflows/build.yml
    with:
      test: true
      package: true
