name: release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  build-test-publish:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      build-type: Release
      test: true
      package: true
      publish: true

  build-docs:
    uses: ./.github/workflows/build-docs.yml
    secrets: inherit
    with:
      version: ${{ github.ref }}
